### ISSUE TITLE
chillup support

### ISSUE THREAD

**Issue by Cokemonkey11** [StN-NL/CustomHeroAbilities#1]
```
$ chillup --index

To make your own wurst library searchable, it must be:

-   Uploaded to GitHub in a public repository
-   Tagged with the `wurst` and `dependency` topics
```

https://github.com/Cokemonkey11/chillup

**Comment by StN-NL** [comment]
Now that it is searchable, how to add it using Wurst Setup? Getting the following error: "Updating dependency - CustomHeroAbilities ..error!"

**Comment by Cokemonkey11** [comment]
@StN-NL it works fine for me
![image](https://user-images.githubusercontent.com/1418966/145656651-10b04544-c941-4017-b0a4-73580c45460c.png)
